translation of the guide overview
AcademyIFCE/swift-book pull request #535
Opened 2022-10-04 17:06 UTC by milenaalcantara

2022-10-04 19:04 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md
> +Você não precisa importar uma biblioteca à parte para uma funcionalidade como entrada e saída ou manipulação de uma cadeia de caracteres.
substituir cadeia de caracteres por string mesmo

2022-10-04 19:12 UTC, GabrielaBezerra requested changes
Traduzir o primeiro paragrafo, o @Comment, e o comentário no código também.
No mais, tá perfeito.

2022-10-04 19:33 UTC, milenaalcantara commented
Vou traduzir, mas a Matheus tinha passado que nao era pra traduzir o que
está dentro do @comment. Acho melhor tu avisar no discord 🫠

Em ter., 4 de out. de 2022 às 16:12, Gabriela Bezerra <
***@***.***> escreveu:

> ***@***.**** requested changes on this pull request.
>
> Traduzir o primeiro paragrafo, o @comment <https://github.com/comment>, e
> o comentário no código também.
> No mais, tá perfeito.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AcademyIFCE/swift-book/pull/535#pullrequestreview-1130487180>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASALDSWARBNRGZ2S6RERN3DWBR6R3ANCNFSM6AAAAAAQ4YVK44>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-04 19:48 UTC, GabrielaBezerra commented
Acabei de conversar com ele, de boas sem traduzir o @Comment 👍🏼

2022-10-05 23:47 UTC, GabrielaBezerra approved these changes

2022-10-05 23:50 UTC, merged