Basic operators/assignment operator
AcademyIFCE/swift-book pull request #536
Opened 2022-10-04 18:16 UTC by milenaalcantara

Translated Assignments Operators section by Basic Operators topic

2022-10-04 19:52 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
>  The following statement isn't valid:
Remover esse trecho em ingles

2022-10-04 19:54 UTC, GabrielaBezerra requested changes
Ficou massa! Só remover aquele trecho em ingles ali e pronto

2022-10-04 20:29 UTC, milenaalcantara commented
ok


Em ter., 4 de out. de 2022 às 16:54, Gabriela Bezerra <
***@***.***> escreveu:

> ***@***.**** requested changes on this pull request.
>
> Ficou massa! Só remover aquele trecho em ingles ali e pronto
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AcademyIFCE/swift-book/pull/536#pullrequestreview-1130533778>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASALDSVIOHN66AYF5YXAFA3WBSDOTANCNFSM6AAAAAAQ42J4FY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-04 20:46 UTC, milenaalcantara commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
>  The following statement isn't valid:
prontinho

2022-10-04 21:01 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
>  ## Assignment Operator
Muda pra Operador de Atribuição

2022-10-04 21:01 UTC, GabrielaBezerra requested changes
Percebi que faltou mais essa tradução

2022-10-06 11:38 UTC, milenaalcantara commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
>  ## Assignment Operator
prontinho

2022-10-07 11:39 UTC, GabrielaBezerra approved these changes

2022-10-07 12:27 UTC, merged