Translate guided tour - concurrency
AcademyIFCE/swift-book pull request #537
Opened 2022-10-04 18:43 UTC by Natalialocatelli

#7

2022-10-04 19:56 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md
> +Use _async_ para marcar uma função que é executada de forma assíncrona.
nesse caso, como async é uma keyword, mantém `async` com as crases. Da mesma forma `await`. Se tiver com crase é pra manter crase.

2022-10-04 19:59 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md
> +Quando você usar o valor que ele retorna, escreva _await_.
aqui se refere a função, então é deixando-a em vez de deixando-o. E ela retorna em vez de ele retorna.

2022-10-04 20:00 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md
> +Use _Task_ para chamar funções assíncronas de código síncrono,
mesma coisa, mantém as crases

2022-10-04 20:24 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md
> +Use _async let_ para chamar uma função assíncrona,
mantém as cases

2022-10-04 20:25 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/GuidedTour/GuidedTour.md
> +Você marca uma chamada para uma função assíncrona escrevendo _await_ na frente dela.
mantém as crases

2022-10-04 20:27 UTC, GabrielaBezerra requested changes
Ta muito massa! Só duas coisas:
1. Manter as crases em vez dos underlines e da pra aprovar
2. Traduzir o comentário do ultimo exemplo de código da sessão Concurrency

2022-10-04 20:31 UTC, Natalialocatelli commented
Corrigido! #7

2022-10-05 11:26 UTC, mtsrodrigues approved these changes

2022-10-05 23:57 UTC, GabrielaBezerra approved these changes

2022-10-05 23:57 UTC, merged