Basic operators/arithmetic operators
AcademyIFCE/swift-book pull request #538
Opened 2022-10-04 18:59 UTC by milenaalcantara

translated Arithmetic Operators section by Basic Operators topic

2022-10-04 20:28 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
> +Swift suport os 4 *operadores aritméticos* padrões para todos os tipos de números:
suporta

2022-10-04 20:29 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
> +1 + 2       // igual à 3
acho que não tem crase :P

2022-10-04 20:34 UTC, milenaalcantara commented
foi


Em ter., 4 de out. de 2022 às 17:29, Gabriela Bezerra <
***@***.***> escreveu:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
> <https://github.com/AcademyIFCE/swift-book/pull/538#discussion_r987301895>
> :
>
> > @@ -148,18 +148,19 @@ Swift helps you to avoid these kinds of errors in your code.
>
>
>
>  ## Arithmetic Operators
>
>
>
> +Swift suport os 4 *operadores aritméticos* padrões para todos os tipos de números:
>
>
> suporta
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AcademyIFCE/swift-book/pull/538#pullrequestreview-1130572183>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASALDSWM4QHOWD4MLCBR5RLWBSHQ3ANCNFSM6AAAAAAQ43LFUU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-04 20:35 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
> +(como por exemplo `a &+ b`). Veja <doc:AdvancedOperators#Overflow-Operators>.
Esse trecho é difícil, porque _overflow_ é um termo técnico né?
Talvez valha a pena fazer assim:

Diferente dos operadores aritméticos em C e Objective-C,
 os de Swift não permitem valores ultrapassem o tamanho padrão definido (não permite _overflow_).
 Você pode optar por avaliar o comportamento de _overflow_ usando os operadores de overflow do Swift
 (como por exemplo `a &+ b`). Veja <doc:AdvancedOperators#Overflow-Operators>.

2022-10-04 20:36 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
> +"olá, " + "mundo"  // é igual à "olá, mundo"
sem crase xD

2022-10-04 20:36 UTC, GabrielaBezerra requested changes
Ta muito show! Mas tenho algumas sugestões nos comentários, olha lá!

2022-10-04 20:38 UTC, milenaalcantara commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
> +(como por exemplo `a &+ b`). Veja <doc:AdvancedOperators#Overflow-Operators>.
Vou fazer isso

2022-10-04 20:50 UTC, milenaalcantara commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
> +1 + 2       // igual à 3
retirei hehe

2022-10-04 21:02 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
>  ## Arithmetic Operators
Operadores Aritméticos

2022-10-04 21:02 UTC, GabrielaBezerra requested changes
Ficou faltando traduzir o título

2022-10-06 11:33 UTC, milenaalcantara commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
> +(como por exemplo `a &+ b`). Veja <doc:AdvancedOperators#Overflow-Operators>.
pronto

2022-10-06 11:34 UTC, milenaalcantara commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
> +"olá, " + "mundo"  // é igual à "olá, mundo"
pronto

2022-10-06 11:34 UTC, milenaalcantara commented on Sources/TSPL/TSPL.docc/LanguageGuide/BasicOperators.md
>  ## Arithmetic Operators
pronto

2022-10-07 12:37 UTC, GabrielaBezerra approved these changes

2022-10-07 12:37 UTC, merged