nested-types/referring-to-nested-types
AcademyIFCE/swift-book pull request #592
Opened 2022-10-07 11:46 UTC by NicolasBarbosa0

Link of the issue: https://github.com/AcademyIFCE/swift-book/issues/41

2022-10-07 11:51 UTC, carolpb requested changes

2022-10-07 11:51 UTC, carolpb commented on Sources/TSPL/TSPL.docc/LanguageGuide/NestedTypes.md
> +Para usar um tipo aninhado fora do seu contexto de definição
vírgula depois de "definição"

2022-10-07 11:51 UTC, carolpb commented on Sources/TSPL/TSPL.docc/LanguageGuide/NestedTypes.md
> +Para usar um tipo aninhado fora do seu contexto de definição
só uma micro mudança, tá ótimo!

2022-10-10 14:25 UTC, NicolasBarbosa0 commented
Alteração feita

2022-10-21 14:17 UTC, mtsrodrigues approved these changes

2022-10-21 14:17 UTC, merged