Initialization/Initializer Inheritance and Overriding
AcademyIFCE/swift-book pull request #597
Opened 2022-10-07 13:00 UTC by canogg

2022-10-07 16:28 UTC, paahbss commented
@canogg  lembra de referenciar a issue aqui nesse pull request, assim quando ele for mergeado a issue será fechada ;) 

Para fazer isso basta dar uma olhadinha [aqui](https://docs.github.com/pt/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) na documentação

2022-10-10 20:05 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
>  ### Initializer Inheritance and Overriding
Traduzir o título também

2022-10-10 20:06 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
>  @Comment {
Remover os @Comment

2022-10-10 20:09 UTC, GabrielaBezerra requested changes
Deixei comentadas duas pequenas mudanças: traduzir o título e tirar os @ comment do tópico. No mais tá muito massa! Valeu pela tradução!

2022-10-24 21:00 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
> +### Herança e substituição do inicializador
Override = sobrescrever
Overriding = sobrescrita

2022-10-24 21:01 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
> +você está efetivamente fornecendo uma substituição desse inicializador designado.
trocar substituição por sobrescrita

2022-10-24 21:01 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
> +Isso é verdade mesmo se você estiver substituindo um inicializador padrão fornecido automaticamente,
sobrescrevendo em vez de substituindo

2022-10-24 21:03 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
> +Tal como acontece com uma propriedade, método ou subscrito substituído,
pode colocar propriedade, método ou _subscript_ sobrescrito

2022-10-24 21:03 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
> +a superclasse tem um inicializador designado correspondente a ser substituído,
substituído = sobrescrito

2022-10-24 21:03 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
> +e valida se os parâmetros do inicializador de substituição foram especificados conforme o esperado.
inicializador sobrescrito

2022-10-24 21:04 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
> +> Nota: Você sempre escreve o modificador `override` ao substituir um inicializador designado de superclasse,
ao sobrescrever em vez de ao substituir

2022-10-24 21:05 UTC, GabrielaBezerra commented on Sources/TSPL/TSPL.docc/LanguageGuide/Initialization.md
> +Portanto, sua subclasse não está (estritamente falando) fornecendo uma substituição do inicializador da superclasse.
sobrescrita em vez de substituição

2022-10-24 21:09 UTC, GabrielaBezerra requested changes
Só mais uma pequena correção: override deve ser traduzido como sobrescrita em vez de substituição. Esse é o termo correto em português usado em POO para override https://pt.wikipedia.org/wiki/Redefinição_de_métodos

2022-10-26 15:35 UTC, GabrielaBezerra approved these changes
Obrigada!

2022-10-28 15:00 UTC, merged